<a href="https://colab.research.google.com/github/SHREE101020/CIE-1/blob/main/PIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [4]:
iris=load_iris()
x=iris.data
y=iris.target

In [5]:
df=pd.DataFrame(data=x,columns=iris.feature_names)
df['species']=pd.Categorical.from_codes(y,iris.target_names)
print(df['species'])
print(df.describe())
print(df.shape)
print(df.info())
print(df['species'].value_counts())

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.

In [6]:
print(df.isnull().sum())

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64


In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)
print(x_train)
print(y_train)

[[5.4 3.  4.5 1.5]
 [4.6 3.2 1.4 0.2]
 [6.7 2.5 5.8 1.8]
 [4.9 3.  1.4 0.2]
 [5.  2.3 3.3 1. ]
 [6.7 3.3 5.7 2.5]
 [7.2 3.2 6.  1.8]
 [5.8 2.6 4.  1.2]
 [6.7 3.1 4.7 1.5]
 [5.1 3.8 1.6 0.2]
 [7.7 3.  6.1 2.3]
 [5.  3.4 1.5 0.2]
 [6.7 3.1 4.4 1.4]
 [5.4 3.7 1.5 0.2]
 [6.4 2.8 5.6 2.2]
 [4.3 3.  1.1 0.1]
 [5.7 4.4 1.5 0.4]
 [5.9 3.  4.2 1.5]
 [6.1 3.  4.6 1.4]
 [6.5 3.  5.5 1.8]
 [5.2 3.5 1.5 0.2]
 [5.6 2.5 3.9 1.1]
 [7.7 2.6 6.9 2.3]
 [6.3 3.4 5.6 2.4]
 [6.2 2.9 4.3 1.3]
 [5.7 2.9 4.2 1.3]
 [5.  3.5 1.6 0.6]
 [5.6 2.9 3.6 1.3]
 [6.  2.2 5.  1.5]
 [5.5 2.6 4.4 1.2]
 [4.6 3.4 1.4 0.3]
 [5.6 3.  4.1 1.3]
 [5.1 3.4 1.5 0.2]
 [6.4 2.9 4.3 1.3]
 [6.8 3.  5.5 2.1]
 [6.7 3.  5.  1.7]
 [6.5 3.2 5.1 2. ]
 [6.  3.4 4.5 1.6]
 [4.9 3.1 1.5 0.1]
 [4.9 2.5 4.5 1.7]
 [6.9 3.2 5.7 2.3]
 [5.4 3.4 1.5 0.4]
 [5.5 2.4 3.8 1.1]
 [6.3 3.3 6.  2.5]
 [5.  3.6 1.4 0.2]
 [6.1 3.  4.9 1.8]
 [6.5 2.8 4.6 1.5]
 [5.9 3.  5.1 1.8]
 [6.3 2.5 4.9 1.5]
 [4.9 3.6 1.4 0.1]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [7.1 3.  5.

In [9]:
clf=DecisionTreeClassifier(random_state=42)
clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [10]:
yperd=clf.predict(x_test)
yperd

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2])

In [12]:
accuracy=accuracy_score(y_test,yperd)
print("Accuracy Score=",accuracy)

Accuracy Score= 0.9666666666666667
